
export = ActionPlaceholderEnum;
enum ActionPlaceholderEnum {
	PRODUCT_NAME,
	DISCOUNT_VALUE,
	COMMERCIAL_CHANELS,
	PRODUCT_PRICE,
	PRICE_CHANGE,
	PRODUCT_PACKAGE_OPTION,
	PRODUCT_SKU,
	PRODUCT_STOCKING_TIME,
	CUSTOMERS_FOR_PRODUCT,
	PRODUCT_MARGIN_RATE,
	PRODUCT_CONVERSION_RATE,
	CATEGORY_NAME,
	CATEGORY_CHANGE_IN_SALE,
	BENEFITS
}
