
export import QuadrantValueEnum = require('./QuadrantValueEnum');
export import QuadrantValueFactory = require('./QuadrantValueFactory');
export import Signal = require('./Signal');
export import SignalThreshold = require('./SignalThreshold');
export import Situation = require('./Situation');
export import Matrix = require('./Matrix');
export import MatrixProduct = require('./MatrixProduct');
export import MatrixCustomer = require('./MatrixCustomer');
export import MatrixChannel = require('./MatrixChannel');
export import MatrixCategory = require('./MatrixCategory');
export import MatrixEShop = require('./MatrixEShop');
export import ColumnEnum = require('./ColumnEnum');
export import ColumnFactory = require('./ColumnFactory');
export import QuadrantDescription = require('./QuadrantDescription');
export import MatrixDescription = require('./MatrixDescription');
QuadrantValueEnum;
QuadrantValueFactory;
Signal;
SignalThreshold;
Situation;
Matrix;
MatrixProduct;
MatrixCustomer;
MatrixChannel;
MatrixCategory;
MatrixEShop;
ColumnEnum;
ColumnFactory;
QuadrantDescription;
MatrixDescription;
