
export import User = require('./User');
export import EShop = require('./EShop');
export import Company = require('./Company');
export import AuthHash = require('./AuthHash');
export import Authenticate = require('./Authenticate');
export import AuthTypeEnum = require('./AuthTypeEnum');
export import ServiceTypeEnum = require('./ServiceTypeEnum');
export import ServiceTypeFactory = require('./ServiceTypeFactory');
export import ServiceConnection = require('./ServiceConnection');
export import Matrix = require('./Matrix');
export import Product = require('./Product');
export import Customer = require('./Customer');
export import Category = require('./Category');
export import Channel = require('./Channel');
export import MatrixLoad = require('./MatrixLoad');
User;
EShop;
Company;
AuthHash;
Authenticate;
AuthTypeEnum;
ServiceTypeEnum;
ServiceTypeFactory;
ServiceConnection;
Matrix;
Product;
Customer;
Category;
Channel;
MatrixLoad;
