
export import User = require('./User');
export import EShop = require('./EShop');
export import Company = require('./Company');
export import AuthHash = require('./AuthHash');
export import Authenticate = require('./Authenticate');
export import AuthTypeEnum = require('./AuthTypeEnum');
export import ServiceTypeEnum = require('./ServiceTypeEnum');
export import ServiceTypeFactory = require('./ServiceTypeFactory');
export import ServiceConnection = require('./ServiceConnection');
export import Matrix = require('./Matrix');
User;
EShop;
Company;
AuthHash;
Authenticate;
AuthTypeEnum;
ServiceTypeEnum;
ServiceTypeFactory;
ServiceConnection;
Matrix;
