
INSERT INTO warehouse."ccountry" ("countryidiso", "countrynameen") VALUES
('CZ',	'Czech');
INSERT INTO warehouse."eshop" ("eshopid", "countryidiso", "companyid", "eshopurl", "eshopname", "datecreated") VALUES
(1,	'CZ',	NULL,	'farfalia.com',	'Farfalia',	'2015-03-25 21:02:03.098183+01');

INSERT INTO analytical."cmatrix" ("matrixtype", "description") VALUES
('MLC1',	''),
('MLC2',	''),
('MLC3',	''),
('MLC4',	''),
('MLC5',	''),
('MLC6',	''),
('MLC8',	''),
('MLC9',	''),
('MLC10',	''),
('MLC11',	''),
('MLC12',	''),
('MLC13',	''),
('MLC14',	''),
('MLC15',	''),
('MLC20',	''),
('MLC21',	''),
('MLC22',	''),
('MLC23',	''),
('MLC24',	''),
('MLC25',	''),
('MLC26',	''),
('MLC27',	''),
('MLC28',	''),
('MLC29',	''),
('MLC30',	''),
('MLC31',	''),
('MLC32',	''),
('MLC33',	''),
('MLC34',	''),
('MLC35',	''),
('MLC36',	''),
('MLC37',	''),
('MLC38',	'');

INSERT INTO feed."feedcolumn" ("feedcolumnid", "feedcode", "entity", "property", "datatype", "maxlength") VALUES
(229,	'SITEMAP',	'SITEMAP',	'lastMod',	'DATE',	NULL),
(252,	'HEUREKA',	'HEUREKA_DELIVERY',	'deliveryPrice',	'HYBRID_FLOAT',	NULL),
(253,	'HEUREKA',	'HEUREKA_DELIVERY',	'deliveryPriceCod',	'HYBRID_FLOAT',	NULL),
(231,	'SITEMAP',	'SITEMAP',	'priority',	'STRICT_FLOAT',	NULL),
(241,	'HEUREKA',	'HEUREKA_PRODUCT',	'priceVat',	'HYBRID_FLOAT',	NULL),
(228,	'SITEMAP',	'SITEMAP',	'loc',	'STRING',	2048),
(230,	'SITEMAP',	'SITEMAP',	'changefreq',	'STRING',	20),
(243,	'HEUREKA',	'HEUREKA_PARAM',	'paramName',	'STRING',	50),
(244,	'HEUREKA',	'HEUREKA_PARAM',	'value',	'STRING',	50),
(251,	'HEUREKA',	'HEUREKA_DELIVERY',	'deliveryId',	'STRING',	50),
(249,	'HEUREKA',	'HEUREKA_PRODUCT',	'heurekaCpc',	'HYBRID_FLOAT',	NULL),
(254,	'HEUREKA',	'HEUREKA_PRODUCT',	'dues',	'HYBRID_FLOAT',	NULL),
(233,	'HEUREKA',	'HEUREKA_PRODUCT',	'itemId',	'STRING',	255),
(234,	'HEUREKA',	'HEUREKA_PRODUCT',	'productName',	'STRING',	255),
(235,	'HEUREKA',	'HEUREKA_PRODUCT',	'product',	'STRING',	255),
(236,	'HEUREKA',	'HEUREKA_PRODUCT',	'description',	'STRING',	2048),
(237,	'HEUREKA',	'HEUREKA_PRODUCT',	'url',	'STRING',	2048),
(238,	'HEUREKA',	'HEUREKA_PRODUCT',	'imgUrl',	'STRING',	2048),
(239,	'HEUREKA',	'HEUREKA_PRODUCT',	'imgUrlAlternative',	'STRING',	2048),
(240,	'HEUREKA',	'HEUREKA_PRODUCT',	'videoUrl',	'STRING',	2048),
(242,	'HEUREKA',	'HEUREKA_PRODUCT',	'itemType',	'STRING',	50),
(245,	'HEUREKA',	'HEUREKA_PRODUCT',	'manufacturer',	'STRING',	255),
(246,	'HEUREKA',	'HEUREKA_PRODUCT',	'categoryText',	'STRING',	255),
(247,	'HEUREKA',	'HEUREKA_PRODUCT',	'ean',	'STRING',	13),
(248,	'HEUREKA',	'HEUREKA_PRODUCT',	'isbn',	'STRING',	20),
(250,	'HEUREKA',	'HEUREKA_PRODUCT',	'deliveryDate',	'STRING',	20),
(268,	'ZBOZI',	'ZBOZI_PRODUCT',	'unfeatured',	'INTEGER',	NULL),
(260,	'ZBOZI',	'ZBOZI_PRODUCT',	'price',	'STRICT_FLOAT',	NULL),
(261,	'ZBOZI',	'ZBOZI_PRODUCT',	'vat',	'STRICT_FLOAT',	NULL),
(263,	'ZBOZI',	'ZBOZI_PRODUCT',	'maxCpc',	'STRICT_FLOAT',	NULL),
(264,	'ZBOZI',	'ZBOZI_PRODUCT',	'maxCpcSearch',	'STRICT_FLOAT',	NULL),
(265,	'ZBOZI',	'ZBOZI_PRODUCT',	'dues',	'STRICT_FLOAT',	NULL),
(262,	'ZBOZI',	'ZBOZI_PRODUCT',	'priceVat',	'STRICT_FLOAT',	NULL),
(255,	'ZBOZI',	'ZBOZI_PRODUCT',	'product',	'STRING',	255),
(256,	'ZBOZI',	'ZBOZI_PRODUCT',	'productName',	'STRING',	255),
(257,	'ZBOZI',	'ZBOZI_PRODUCT',	'description',	'STRING',	2048),
(258,	'ZBOZI',	'ZBOZI_PRODUCT',	'url',	'STRING',	2048),
(259,	'ZBOZI',	'ZBOZI_PRODUCT',	'imgUrl',	'STRING',	2048),
(266,	'ZBOZI',	'ZBOZI_PRODUCT',	'deliveryDate',	'STRING',	50),
(267,	'ZBOZI',	'ZBOZI_PRODUCT',	'shopDepots',	'STRING',	50),
(269,	'ZBOZI',	'ZBOZI_PRODUCT',	'itemType',	'STRING',	50),
(270,	'ZBOZI',	'ZBOZI_PRODUCT',	'extraMessage',	'STRING',	50),
(271,	'ZBOZI',	'ZBOZI_PRODUCT',	'manufacturer',	'STRING',	255),
(272,	'ZBOZI',	'ZBOZI_PRODUCT',	'categoryText',	'STRING',	255),
(273,	'ZBOZI',	'ZBOZI_PRODUCT',	'ean',	'STRING',	13),
(274,	'ZBOZI',	'ZBOZI_PRODUCT',	'productNo',	'STRING',	50),
(275,	'ZBOZI',	'ZBOZI_PRODUCT',	'productNameExt',	'STRING',	255);

INSERT INTO warehouse."eshopsettings" ("settingsid", "eshopid", "datarefreshperiod", "datestart", "datechanged") VALUES
(1,	1,	'1day',	now() - interval '7day',	now());
